
class CashRegister
 attr_accessor :discount, :price , :item, :total
 #NOTICE: total not needed it accessor to create a discount
 #&& 'll be overridden by the next @total I define later on But since generated by test i 'll leave it'
  def initialize(discount=nil)
    @total = 0
    @discount = discount
    @items =  []
  end

  def add_item(title, price, quantity=1)
    quantity.times { |item| @items << title }
    self.total += price * quantity
    @items
  end

  def apply_discount
    # @apply = @total * (@discount/100.00)
    if self.discount != 0
       self.total = total-(total*(discount/100.00))
    "After the discount, the total comes to $#{@total.to_i}."
    else
     "There is no discount to apply."
   end
end
 #
 def items
 @items
 end

end
